model:
  labelmap_path: /snap/frigate/current/frigate/labelmap.txt
mqtt:
  enabled: False
  host: localhost
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@localhost:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
