model:
  labelmap_path: /snap/frigate/current/frigate/labelmap.txt
mqtt:
  enabled: False
  host: localhost
cameras:
  test:
    ffmpeg:
      inputs:
        - input_args: "-re -stream_loop -1 -fflags +genpts"
          path: /snap/frigate/current/frigate/black.mp4
          roles:
            - rtmp
            - record
            - detect
    detect:
      width: 2
      height: 2
      fps: 1
      enabled: False
    record:
      enabled: False
detectors:
  cpu1:
    type: cpu
    num_threads: 3
    model:
      path: "/snap/frigate/current/frigate/cpu_model.tflite"
      labelmap_path: /snap/frigate/current/frigate/labelmap.txt
